### ISSUE TITLE
Last remaining .cuda()

### ISSUE THREAD

**Issue by egpbos** [spokenlanguage/platalea#1]
There's still one remaining explicit `.cuda()` call in decoders.py in TextDecoder. It has a `use_cuda` boolean parameter and checks that before calling `.cuda()` on the model. Is the `use_cuda` parameter actually used? Or would it preferable to remove the parameter and also switch to automatic device detection as we're using everywhere else now?

**Comment by bhigy** [comment]
It is used on line 196 of the same file. The device used for the rest of the experiment should also be used here.

**Comment by egpbos** [comment]
As I'm finding out while working on #4, this causes an error when running pip experiments:

```
INFO:root:Extracting ASR/SLT transcriptions
Traceback (most recent call last):
  File "/Users/pbos/sw/miniconda3/envs/platalea/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/pbos/sw/miniconda3/envs/platalea/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/pbos/projects/spokenLanguage/platalea/platalea/experiments/flickr8k/pip_seq.py", line 60, in <module>
    hyp_asr, ref_asr = extract_trn(net, ds, use_beam_decoding=True)
  File "/Users/pbos/projects/spokenLanguage/platalea/platalea/utils/extract_transcriptions.py", line 16, in extract_trn
    hyp = net.transcribe(d['audio'], beam_size=10).tolist()
  File "/Users/pbos/projects/spokenLanguage/platalea/platalea/asr.py", line 52, in transcribe
    preds = self.TextDecoder.beam_search(enc_out, beam_size)
  File "/Users/pbos/projects/spokenLanguage/platalea/platalea/decoders.py", line 197, in beam_search
    input = input.cuda()
  File "/Users/pbos/sw/miniconda3/envs/platalea/lib/python3.8/site-packages/torch/cuda/__init__.py", line 194, in _lazy_init
    _check_driver()
  File "/Users/pbos/sw/miniconda3/envs/platalea/lib/python3.8/site-packages/torch/cuda/__init__.py", line 92, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

I will replace it with `platalea.hardware.device()` like everywhere else.
