### ISSUE TITLE
No get_last_lr method in scheduler

### ISSUE THREAD

**Issue by bhigy** [spokenlanguage/platalea#49]
I tried to run the `basic_default` experiment and get following error:
```
Traceback (most recent call last):
  File "basic_default.py", line 49, in <module>
    M.experiment(net, data, run_config)
  File "/home/bjrhigy/dev/platalea/platalea/basic.py", line 125, in experiment
    wandb_step_output["last_lr"] = scheduler.get_last_lr()[0]
AttributeError: 'LambdaLR' object has no attribute 'get_last_lr'
```
@egpbos and @cwmeijer, this seems related to the new code for wandb. Did you experience that?

**Comment by egpbos** [comment]
Weird. What scheduler are you using there?

**Comment by bhigy** [comment]
Found the culprit. This is due to the version of pytorch I am using (1.2, the one defined in `requirements.txt`). Upgrading to 1.7.1 solves this issue but I get another error then:
```
Traceback (most recent call last):
  File "basic_default.py", line 49, in <module>
    M.experiment(net, data, run_config)
  File "/home/bjrhigy/dev/platalea/platalea/basic.py", line 115, in experiment
    loss = net.cost(item)
  File "/home/bjrhigy/dev/platalea/platalea/basic.py", line 34, in cost
    speech_enc = self.SpeechEncoder(item['audio'], item['audio_len'])
  File "/home/bjrhigy/.virtualenvs/platalea/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/bjrhigy/dev/platalea/platalea/encoders.py", line 110, in forward
    x.transpose(2, 1), length, batch_first=True, enforce_sorted=False)
  File "/home/bjrhigy/.virtualenvs/platalea/lib/python3.7/site-packages/torch/nn/utils/rnn.py", line 244, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor
```
I have removed the W&B line giving issue for now, so that master can run without bug.

**Comment by bhigy** [comment]
I think the bug with 1.7.1 has been fixed by Patrick. We should check again if this version works now and switch to that.

**Comment by cwmeijer** [comment]
This should already be fixed in zerospeech branch.
